In [39]:
import numpy as np 
import pandas as pd

In [40]:
df = pd.read_csv(r'E:\Study\Analytix Labs\Projects\project\3. Network Intrusion Detection System\NSL_Dataset\Train.txt',header = None)

In [41]:
df_test = pd.read_csv(r'E:\Study\Analytix Labs\Projects\project\3. Network Intrusion Detection System\NSL_Dataset\Test.txt',header = None)

In [42]:
df_test.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
2,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.0,0.0,0.00,0.00,normal,21
3,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.0,0.0,0.00,0.00,saint,15
4,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.0,0.0,0.83,0.71,mscan,11

In [43]:
df.shape

(125973, 43)

In [44]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [45]:
cols = ["duration","protocol_type","service","flag","src_bytes","dst_bytes","land", "wrong_fragment","urgent","hot","num_failed_logins","logged_in", "num_compromised","root_shell","su_attempted","num_root","num_file_creations", "num_shells","num_access_files","num_outbound_cmds","is_host_login", "is_guest_login","count","srv_count","serror_rate", "srv_serror_rate", "rerror_rate","srv_rerror_rate","same_srv_rate", "diff_srv_rate", "srv_diff_host_rate","dst_host_count","dst_host_srv_count","dst_host_same_srv_rate", "dst_host_diff_srv_rate","dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate", "dst_host_rerror_rate","dst_host_srv_rerror_rate","attack", "last_flag"]

In [46]:
df.columns = cols

In [47]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,last_flag
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [48]:
df_test.columns = cols

In [49]:
df_test.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,last_flag
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
2,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.0,0.0,0.00,0.00,normal,21
3,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.0,0.0,0.00,0.00,saint,15
4,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.0,0.0,0.83,0.71,mscan,11

In [51]:
df_test.shape

(22544, 43)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 43 columns):
duration                       125973 non-null int64
protocol_type                  125973 non-null object
service                        125973 non-null object
flag                           125973 non-null object
src_bytes                      125973 non-null int64
dst_bytes                      125973 non-null int64
land                           125973 non-null int64
wrong_fragment                 125973 non-null int64
urgent                         125973 non-null int64
hot                            125973 non-null int64
num_failed_logins              125973 non-null int64
logged_in                      125973 non-null int64
num_compromised                125973 non-null int64
root_shell                     125973 non-null int64
su_attempted                   125973 non-null int64
num_root                       125973 non-null int64
num_file_creations             125973 non-null int64
num_shells                     125973 non-null int64
num_access_files               125973 non-null int64
num_outbound_cmds              125973 non-null int64
is_host_login                  125973 non-null int64
is_guest_login                 125973 non-null int64
count                          125973 non-null int64
srv_count                      125973 non-null int64
serror_rate                    125973 non-null float64
srv_serror_rate                125973 non-null float64
rerror_rate                    125973 non-null float64
srv_rerror_rate                125973 non-null float64
same_srv_rate                  125973 non-null float64
diff_srv_rate                  125973 non-null float64
srv_diff_host_rate             125973 non-null float64
dst_host_count                 125973 non-null int64
dst_host_srv_count             125973 non-null int64
dst_host_same_srv_rate         125973 non-null float64
dst_host_diff_srv_rate         125973 non-null float64
dst_host_same_src_port_rate    125973 non-null float64
dst_host_srv_diff_host_rate    125973 non-null float64
dst_host_serror_rate           125973 non-null float64
dst_host_srv_serror_rate       125973 non-null float64
dst_host_rerror_rate           125973 non-null float64
dst_host_srv_rerror_rate       125973 non-null float64
attack                         125973 non-null object
last_flag                      125973 non-null int64
dtypes: float64(15), int64(24), object(4)
memory usage: 41.3+ MB

In [53]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22544 entries, 0 to 22543
Data columns (total 43 columns):
duration                       22544 non-null int64
protocol_type                  22544 non-null object
service                        22544 non-null object
flag                           22544 non-null object
src_bytes                      22544 non-null int64
dst_bytes                      22544 non-null int64
land                           22544 non-null int64
wrong_fragment                 22544 non-null int64
urgent                         22544 non-null int64
hot                            22544 non-null int64
num_failed_logins              22544 non-null int64
logged_in                      22544 non-null int64
num_compromised                22544 non-null int64
root_shell                     22544 non-null int64
su_attempted                   22544 non-null int64
num_root                       22544 non-null int64
num_file_creations             22544 non-null int64
num_shells                     22544 non-null int64
num_access_files               22544 non-null int64
num_outbound_cmds              22544 non-null int64
is_host_login                  22544 non-null int64
is_guest_login                 22544 non-null int64
count                          22544 non-null int64
srv_count                      22544 non-null int64
serror_rate                    22544 non-null float64
srv_serror_rate                22544 non-null float64
rerror_rate                    22544 non-null float64
srv_rerror_rate                22544 non-null float64
same_srv_rate                  22544 non-null float64
diff_srv_rate                  22544 non-null float64
srv_diff_host_rate             22544 non-null float64
dst_host_count                 22544 non-null int64
dst_host_srv_count             22544 non-null int64
dst_host_same_srv_rate         22544 non-null float64
dst_host_diff_srv_rate         22544 non-null float64
dst_host_same_src_port_rate    22544 non-null float64
dst_host_srv_diff_host_rate    22544 non-null float64
dst_host_serror_rate           22544 non-null float64
dst_host_srv_serror_rate       22544 non-null float64
dst_host_rerror_rate           22544 non-null float64
dst_host_srv_rerror_rate       22544 non-null float64
attack                         22544 non-null object
last_flag                      22544 non-null int64
dtypes: float64(15), int64(24), object(4)
memory usage: 7.4+ MB

In [54]:
# for training data 
a = []

for x in df.columns.to_list():
    if df[x].dtypes == 'object':
        a.append(x)
        
cat_df = df[a]
cat_df
y_train = cat_df.attack
cat_df = cat_df.drop(columns=['attack'])

In [55]:
# for testing data 
a = []

for x in df_test.columns.to_list():
    if df_test[x].dtypes == 'object':
        a.append(x)
        
cat_df_test = df_test[a]
y_test = cat_df_test.attack
cat_df_test = cat_df_test.drop(columns=['attack'])

In [56]:
#creating dummies of categorical data for training data
def create_dummies( df, colname ):
    col_dummies = pd.get_dummies(df[colname], prefix=colname, drop_first=True)
    df = pd.concat([df, col_dummies], axis=1)
    df.drop( colname, axis = 1, inplace = True )
    return df


for c_feature in cat_df.columns:
    cat_df[c_feature] = cat_df[c_feature].astype('category')
    cat_df = create_dummies(cat_df , c_feature )
    
for c_feature in cat_df_test.columns:
    cat_df_test[c_feature] = cat_df_test[c_feature].astype('category')
    cat_df_test = create_dummies(cat_df_test , c_feature )

In [57]:
cat_df_test

,protocol_type_tcp,protocol_type_udp,service_X11,service_Z39_50,service_auth,service_bgp,service_courier,service_csnet_ns,service_ctf,service_daytime,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
7,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
8,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
11,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
12,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
14,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
15,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
16,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
17,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
19,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
20,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
21,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
23,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
24,1,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
26,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
27,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
29,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22514,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22515,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
22516,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22517,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22518,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22519,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22520,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
22521,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22522,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22523,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22524,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22525,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
22526,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22527,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22528,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22529,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22530,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
22531,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
22532,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22533,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22534,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
22535,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22536,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
22537,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22538,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22539,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22540,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22541,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22542,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22543,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [58]:
cat_df.shape

(125973, 81)

In [59]:
cat_df_test.shape

(22544, 75)

In [60]:
newdf=df.join(cat_df)
newdf.drop('flag', axis=1, inplace=True)
newdf.drop('protocol_type', axis=1, inplace=True)
newdf.drop('service', axis=1, inplace=True)
# test data
newdf_test=df_test.join(cat_df_test)
newdf_test.drop('flag', axis=1, inplace=True)
newdf_test.drop('protocol_type', axis=1, inplace=True)
newdf_test.drop('service', axis=1, inplace=True)
print(newdf.shape)
print(newdf_test.shape)

(125973, 121)
(22544, 115)

In [61]:
print('Training set:')
for col_name in df.columns:
    if df[col_name].dtypes == 'object' :
        unique_cat = len(df[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

Training set:
Feature 'protocol_type' has 3 categories
Feature 'service' has 70 categories
Feature 'flag' has 11 categories
Feature 'attack' has 23 categories

In [62]:
print('Test set:')
for col_name in df_test.columns:
    if df_test[col_name].dtypes == 'object' :
        unique_cat = len(df_test[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

Test set:
Feature 'protocol_type' has 3 categories
Feature 'service' has 64 categories
Feature 'flag' has 11 categories
Feature 'attack' has 38 categories

In [69]:
ser_cols = [i for i in [x for x in newdf.columns.to_list() if (x.startswith('service'))] if i not in [x for x in newdf_test.columns.to_list() if (x.startswith('service'))]]

In [98]:
newdf_test = newdf_test.reindex(columns = newdf_test.columns.to_list() + ser_cols)

In [100]:
newdf_test[ser_cols] = 0

In [101]:
newdf_test

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_S2,flag_S3,flag_SF,flag_SH,service_aol,service_harvest,service_http_2784,service_http_8001,service_red_i,service_urh_i
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,12983,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,20,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,1,0,15,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,267,14515,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
6,0,1022,387,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
7,0,129,174,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
8,0,327,467,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
9,0,26,157,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
11,0,616,330,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,37,773,364200,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
15,0,350,3610,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
16,0,213,659,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
17,0,246,2090,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
18,0,45,44,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,196,1823,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
23,0,277,1816,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,294,6442,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
27,0,300,440,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
28,0,520,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
29,0,54,51,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22514,0,115,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22515,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22516,0,322,396,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22517,7498,0,44,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22518,0,295,757,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22519,8209,0,15,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22520,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22521,0,1,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22522,0,54540,8314,0,0,0,2,0,1,1,...,0,0,1,0,0,0,0,0,0,0
22523,0,289,9522,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22524,15,45,214,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22525,2064,55744,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
22526,0,169,4997,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22527,0,236,16257,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22528,0,1032,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22529,0,9,139,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22530,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22531,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22532,0,264,14839,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22533,0,274,1623,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22534,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22535,0,280,6087,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22536,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22537,1,2599,293,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22538,0,1032,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22539,0,794,333,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22540,0,317,938,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
22541,0,54540,8314,0,0,0,2,0,1,1,...,0,0,1,0,0,0,0,0,0,0
22542,0,42,42,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22543,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [109]:
Y_train = y_train.replace({ 'normal' : 0, 'neptune' : 1 ,'back': 1, 'land': 1, 'pod': 1, 'smurf': 1, 'teardrop': 1,'mailbomb': 1, 'apache2': 1, 'processtable': 1, 'udpstorm': 1, 'worm': 1,
                           'ipsweep' : 2,'nmap' : 2,'portsweep' : 2,'satan' : 2,'mscan' : 2,'saint' : 2
                           ,'ftp_write': 3,'guess_passwd': 3,'imap': 3,'multihop': 3,'phf': 3,'spy': 3,'warezclient': 3,'warezmaster': 3,'sendmail': 3,'named': 3,'snmpgetattack': 3,'snmpguess': 3,'xlock': 3,'xsnoop': 3,'httptunnel': 3,
                           'buffer_overflow': 4,'loadmodule': 4,'perl': 4,'rootkit': 4,'ps': 4,'sqlattack': 4,'xterm': 4})
Y_test = y_test.replace({ 'normal' : 0, 'neptune' : 1 ,'back': 1, 'land': 1, 'pod': 1, 'smurf': 1, 'teardrop': 1,'mailbomb': 1, 'apache2': 1, 'processtable': 1, 'udpstorm': 1, 'worm': 1,
                           'ipsweep' : 2,'nmap' : 2,'portsweep' : 2,'satan' : 2,'mscan' : 2,'saint' : 2
                           ,'ftp_write': 3,'guess_passwd': 3,'imap': 3,'multihop': 3,'phf': 3,'spy': 3,'warezclient': 3,'warezmaster': 3,'sendmail': 3,'named': 3,'snmpgetattack': 3,'snmpguess': 3,'xlock': 3,'xsnoop': 3,'httptunnel': 3,
                           'buffer_overflow': 4,'loadmodule': 4,'perl': 4,'rootkit': 4,'ps': 4,'sqlattack': 4,'xterm': 4})

In [110]:
newdf['label'] = Y_train
newdf_test['label'] = Y_test

In [112]:
DoS_df = newdf[newdf['label'].isin([0,1])]
Probe_df = newdf[newdf['label'].isin([0,2])]
R2L_df = newdf[newdf['label'].isin([0,3])]
U2R_df = newdf[newdf['label'].isin([0,4])]

In [117]:
DoS_df_test = newdf_test[newdf_test['label'].isin([0,1])]
Probe_df_test = newdf_test[newdf_test['label'].isin([0,2])]
R2L_df_test = newdf_test[newdf_test['label'].isin([0,3])]
U2R_df_test = newdf_test[newdf_test['label'].isin([0,4])]

In [147]:
X_DoS = DoS_df.drop(['label','attack'],1)
Y_DoS = DoS_df.label
X_Probe = Probe_df.drop(['label','attack'],1)
Y_Probe = Probe_df.label
X_R2L = R2L_df.drop(['label','attack'],1)
Y_R2L = R2L_df.label
X_U2R = U2R_df.drop(['label','attack'],1)
Y_U2R = U2R_df.label

# test set

X_DoS_test = DoS_df_test.drop(['label','attack'],1)
Y_DoS_test = DoS_df_test.label
X_Probe_test = Probe_df_test.drop(['label','attack'],1)
Y_Probe_test = Probe_df_test.label
X_R2L_test = R2L_df_test.drop(['label','attack'],1)
Y_R2L_test = R2L_df_test.label
X_U2R_test = U2R_df_test.drop(['label','attack'],1)
Y_U2R_test = U2R_df_test.label

In [148]:
colNames=list(X_DoS)
colNames_test=list(X_DoS_test)

In [149]:
from sklearn import preprocessing
scaler1 = preprocessing.StandardScaler().fit(X_DoS)
X_DoS=scaler1.transform(X_DoS) 
scaler2 = preprocessing.StandardScaler().fit(X_Probe)
X_Probe=scaler2.transform(X_Probe) 
scaler3 = preprocessing.StandardScaler().fit(X_R2L)
X_R2L=scaler3.transform(X_R2L) 
scaler4 = preprocessing.StandardScaler().fit(X_U2R)
X_U2R=scaler4.transform(X_U2R) 
# test data
scaler5 = preprocessing.StandardScaler().fit(X_DoS_test)
X_DoS_test=scaler5.transform(X_DoS_test) 
scaler6 = preprocessing.StandardScaler().fit(X_Probe_test)
X_Probe_test=scaler6.transform(X_Probe_test) 
scaler7 = preprocessing.StandardScaler().fit(X_R2L_test)
X_R2L_test=scaler7.transform(X_R2L_test) 
scaler8 = preprocessing.StandardScaler().fit(X_U2R_test)
X_U2R_test=scaler8.transform(X_U2R_test)

C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  """
C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  import sys
C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  if __name__ == '__main__':
C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  if sys.path[0] == '':
C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.

C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  app.launch_new_instance()
C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.

In [152]:
from sklearn.metrics import roc_auc_score
from sklearn.tree import DecisionTreeRegressor

In [158]:
X_DoS_new = pd.DataFrame(X_DoS, columns = colNames)
X_DoS_testnew = pd.DataFrame(X_DoS_test, columns = colNames)


roc_val = []
for feature in X_DoS_new.columns:
    clf = DecisionTreeRegressor()
    clf.fit(X_DoS_new[feature].to_frame(), Y_DoS)
    Y_scored = clf.predict(X_DoS_testnew[feature].to_frame())
    roc_val.append(roc_auc_score(Y_DoS_test, Y_scored))
    
    
roc_val = pd.Series(roc_val)
roc_val.index = X_DoS_new.columns
roc_val.sort_values(ascending=False).plot.bar(figsize=(20, 8))

In [159]:
selected_feat = roc_val[roc_val > 0.6]
len(selected_feat)
selected_feat
X_DoS_latest = X_DoS_new[selected_feat.index]

In [189]:
X_Probe_new = pd.DataFrame(X_Probe, columns = colNames)
X_Probe_testnew = pd.DataFrame(X_Probe_test, columns = colNames)

roc_val = []
for feature in X_Probe_new.columns:
    clf = DecisionTreeRegressor()
    clf.fit(X_Probe_new[feature].to_frame(), Y_Probe)
    Y_scored = clf.predict(X_Probe_testnew[feature].to_frame())
    roc_val.append(roc_auc_score(Y_Probe_test, Y_scored))
    
roc_val = pd.Series(roc_val)
roc_val.index = X_Probe_new.columns
roc_val.sort_values(ascending=False).plot.bar(figsize=(20, 8))

In [190]:
selected_feat = roc_val[roc_val > 0.55]
len(selected_feat)
selected_feat
X_Probe_latest = X_Probe_new[selected_feat.index]

In [202]:
X_R2L_new = pd.DataFrame(X_R2L, columns = colNames)
X_R2L_testnew = pd.DataFrame(X_R2L_test, columns = colNames)

roc_val = []
for feature in X_R2L_new.columns:
    clf = DecisionTreeRegressor()
    clf.fit(X_R2L_new[feature].to_frame(), Y_R2L)
    Y_scored = clf.predict(X_R2L_testnew[feature].to_frame())
    roc_val.append(roc_auc_score(Y_R2L_test, Y_scored))
    
roc_val = pd.Series(roc_val)
roc_val.index = X_R2L_new.columns
roc_val.sort_values(ascending=False).plot.bar(figsize=(20, 8))

In [203]:
selected_feat = roc_val[roc_val > 0.51]
len(selected_feat)
selected_feat
X_R2L_latest = X_R2L_new[selected_feat.index]

In [216]:
X_U2R_new = pd.DataFrame(X_U2R, columns = colNames)
X_U2R_testnew = pd.DataFrame(X_U2R_test, columns = colNames)

roc_val = []
for feature in X_U2R_new.columns:
    clf = DecisionTreeRegressor()
    clf.fit(X_U2R_new[feature].to_frame(), Y_U2R)
    Y_scored = clf.predict(X_U2R_testnew[feature].to_frame())
    roc_val.append(roc_auc_score(Y_U2R_test, Y_scored))
    
roc_val = pd.Series(roc_val)
roc_val.index = X_U2R_new.columns
roc_val.sort_values(ascending=False).plot.bar(figsize=(20, 8))

In [217]:
selected_feat = roc_val[roc_val > 0.55]
len(selected_feat)
selected_feat
X_U2R_latest = X_U2R_new[selected_feat.index]

In [226]:
from sklearn.tree import DecisionTreeClassifier

In [241]:
# all features
clf_DoS=DecisionTreeClassifier(random_state=0)
clf_Probe=DecisionTreeClassifier(random_state=0)
clf_R2L=DecisionTreeClassifier(random_state=0)
clf_U2R=DecisionTreeClassifier(random_state=0)
clf_DoS.fit(X_DoS_latest, pd.DataFrame(Y_DoS).astype('int'))
clf_Probe.fit(X_Probe_latest, pd.DataFrame(Y_Probe).astype('int'))
clf_R2L.fit(X_R2L_latest, pd.DataFrame(Y_R2L).astype('int'))
clf_U2R.fit(X_U2R_latest, pd.DataFrame(Y_U2R).astype('int'))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [249]:
X_DoS_test_new = pd.DataFrame(X_DoS_test, columns = colNames)
X_Probe_test_new = pd.DataFrame(X_Probe_test, columns = colNames)
X_R2L_test_new = pd.DataFrame(X_R2L_test, columns = colNames)
X_U2R_test_new = pd.DataFrame(X_U2R_test, columns = colNames)

In [251]:
X_DoS_testlatest = X_DoS_test_new[X_DoS_latest.columns]
X_Probe_testlatest = X_Probe_test_new[X_Probe_latest.columns]
X_R2L_testlatest = X_R2L_test_new[X_R2L_latest.columns]
X_U2R_testlatest = X_U2R_test_new[X_U2R_latest.columns]

In [252]:
# Apply the classifier we trained to the test data (which it has never seen before)
clf_DoS.predict(X_DoS_testlatest)

array([1, 1, 0, ..., 0, 0, 0])

In [253]:
Y_DoS_pred=clf_DoS.predict(X_DoS_testlatest)
# Create confusion matrix
pd.crosstab(Y_DoS_test, Y_DoS_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     1
Actual attacks
0                  8667  1044
1                  1306  6154

In [255]:
Y_Probe_pred=clf_Probe.predict(X_Probe_testlatest)
# Create confusion matrix
pd.crosstab(Y_Probe_test, Y_Probe_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     2
Actual attacks
0                  9468   243
2                   919  1502

In [256]:
Y_R2L_pred=clf_R2L.predict(X_R2L_testlatest)
# Create confusion matrix
pd.crosstab(Y_R2L_test, Y_R2L_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0   3
Actual attacks
0                  9708   3
3                  2866  19

In [257]:
Y_U2R_pred=clf_U2R.predict(X_U2R_testlatest)
# Create confusion matrix
pd.crosstab(Y_U2R_test, Y_U2R_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0  4
Actual attacks
0                  9709  2
4                    67  0

In [258]:
from sklearn.model_selection import cross_val_score
from sklearn import metrics
accuracy = cross_val_score(clf_DoS, X_DoS_testlatest, Y_DoS_test, cv=10, scoring='accuracy')
print("Accuracy: %0.5f (+/- %0.5f)" % (accuracy.mean(), accuracy.std() * 2))
precision = cross_val_score(clf_DoS, X_DoS_testlatest, Y_DoS_test, cv=10, scoring='precision')
print("Precision: %0.5f (+/- %0.5f)" % (precision.mean(), precision.std() * 2))

Accuracy: 0.99604 (+/- 0.00265)
Precision: 0.99452 (+/- 0.00551)

In [268]:
accuracy = cross_val_score(clf_Probe, X_Probe_testlatest, Y_Probe_test, cv=10, scoring='accuracy')
print("Accuracy: %0.5f (+/- %0.5f)" % (accuracy.mean(), accuracy.std() * 2))
precision = cross_val_score(clf_Probe, X_Probe_testlatest, Y_Probe_test, cv=10, scoring='precision_macro')
print("Precision: %0.5f (+/- %0.5f)" % (precision.mean(), precision.std() * 2))

Accuracy: 0.99464 (+/- 0.00247)
Precision: 0.99220 (+/- 0.00744)

In [269]:
accuracy = cross_val_score(clf_R2L, X_R2L_testlatest, Y_R2L_test, cv=10, scoring='accuracy')
print("Accuracy: %0.5f (+/- %0.5f)" % (accuracy.mean(), accuracy.std() * 2))
precision = cross_val_score(clf_R2L, X_R2L_testlatest, Y_R2L_test, cv=10, scoring='precision_macro')
print("Precision: %0.5f (+/- %0.5f)" % (precision.mean(), precision.std() * 2))

Accuracy: 0.99587 (+/- 0.00254)
Precision: 0.99394 (+/- 0.00466)

In [270]:
accuracy = cross_val_score(clf_U2R, X_U2R_testlatest, Y_U2R_test, cv=10, scoring='accuracy')
print("Accuracy: %0.5f (+/- %0.5f)" % (accuracy.mean(), accuracy.std() * 2))
precision = cross_val_score(clf_U2R, X_U2R_testlatest, Y_U2R_test, cv=10, scoring='precision_macro',)
print("Precision: %0.5f (+/- %0.5f)" % (precision.mean(), precision.std() * 2))

Accuracy: 0.99918 (+/- 0.00153)
Precision: 0.96443 (+/- 0.07246)